language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t skrillybrick/complex -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true skrillybrick/complex npm run test

after_success:
  - docker build -t skrillybrick/complex-client ./client
  - docker build -t skrillybrick/complex-nginx ./nginx
  - docker build -t skrillybrick/complex-server ./server
  - docker build -t skrillybrick/complex-worker ./worker

  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

  - docker push skrillybrick/complex-client
  - docker push skrillybrick/complex-nginx
  - docker push skrillybrick/complex-server
  - docker push skrillybrick/complex-worker